### ISSUE TITLE
Error loading config file

### ISSUE THREAD

**Issue by pascencio** [VitualReaty/vue-env#2]
Hi,

I'm trying to use the vue-human-env module, in my vue-cli project. My project use webpack-simple template.

When my project start in dev mode, the console throw me this output:

```
ERROR in ./~/vue-human-env/src/index.js
Module build failed: SyntaxError: Unexpected token (18:14)

  16 | 
  17 |     options.forEach(item => {
> 18 |       env = { ...env, ...item }
     |               ^
  19 |     })
  20 | 
  21 |     this._addToEnv(env)

```

Attached my two config file tries. The first one gave me compilation error and the second one seems work.

[env.zip](https://github.com/VitualReaty/vue-human-env/files/820501/env.zip)

Thanks!

**Comment by chasewoo** [comment]
@pascencio Hi,

The first way:
need a babel plugin to parse.  You can see: https://babeljs.io/docs/plugins/transform-object-rest-spread/, or using babel stage-2 plugin.

The second way:
And I update vue-human-env to v2.0.2, use Object.assign instead of { ...env, ...item }.
You can just yarn upgrade vue-human-env. the problem will be solved.

---

You can use the second way.
